
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-express
  template:
    metadata:
      labels:
        app: test-express
    spec:
      containers:
        - name: test_express
          image: test_express:v1
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: test-express-svc
spec:
  ports:
    - name: http-3000
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: test-express
